### ISSUE TITLE
Output results file needs some update

### ISSUE THREAD

**Issue by annamost** [yaksilab/Javid_S2P_codes#5]
Hello Javid, 
sry it took so long but I finally started to use suite2p. 
I found the following things that needs to be changed about the results file to make it easier to use further on (in matlab). 
Note: I can also do most things in matlab, but maybe it would be nice to just have it done as once).

1) Add the automatically deconvoled data from suite2p to the results file 
2) neuronLabels and volume need to be permuted (I get them in matlab out as plane x xcoord x ycoord , but i want them y corr times x corr times plane) 
3) neuron index in the position variable (column 4 needs to start at 1).
4) neuronLabels needs to be update so it counts from 1 to n-neurons over all the planes (i have a code for that in matlab). 

Best,
Anna

**Comment by annamost** [comment]
Also the x and y values of the position are a little weird. I think there is just an issue with the comma...

**Comment by javidaf** [comment]
1. Here I can surly add deconvolved data from suite2p, but you need to know that the deconvolved data is calculated from neuropil subtracted fluorescence, and the trace data that is added is the raw fluorescence and not neuropil subtracted. I can try to so it calculates from raw fluorescence, but then I need to clarify  some otherthings around it. 
2. This is now corrected to the desired shape.
3. I am assuming that the index should start from 1 rather then 0. If so, then it is corrected 
4. This is corrected

**Comment by annamost** [comment]
Hi now I get this error message:
  Input In [18] in <cell line: 11>
    results_obj = Transform_results(directory1)

  File X:\anna\code\Repositories\Javid_S2P_codes\DataST\DataStructureTransform.py:18 in __init__

  File X:\anna\code\Repositories\Javid_S2P_codes\DataST\DataStructureTransform.py:47 in __transform_results

ValueError: could not convert string to float: ''

I tried to update the code. Even deleted it from my local one and cloned it again, but it is not working...

**Comment by annamost** [comment]
I think here is the error when you try to find the factor meter and stuff... 
File X:\anna\code\Repositories\Javid_S2P_codes\Javid_S2P_codes\DataST\DataStructureTransform.py:47 in __transform_results
    factor_meter, dist_z = float(metadata['x.pixel.sz'])*10**7,float(metadata['total.z.distance'])

ValueError: could not convert string to float: ''

**Comment by annamost** [comment]
And comment to 1) I understand. We can also just leave it for now then... thank you

**Comment by annamost** [comment]
I just tried to rerun it and I still have all the same issues with the new code. I tried to reclone the repository in case I made a mistake there... I also just straight up downloaded the code as a ZIP and tired it like that... but I still have all the same issues as before... I don't know if it is a user error or something else...

**Comment by annamost** [comment]
Okay... I finally got it to work... I am still confused... 

One point: I messed up with X and Y corr. So it should be X Y plane sorry not Y X Plane... i always forget that the axis get changed from what I see during my recording to the data... 

I think there also might be something wrong in the neuron labels still, but I will check that if it is an error on my end.

**Comment by annamost** [comment]
Okay. neuron Labels issue :
- i have more neurons in neuron labels than in position. While I have 5000 something neurons for position, neuron Labels goes up to over 6000...

**Comment by annamost** [comment]
Okay... I might have fround the problem. Do you load the data from the combined folder or from the individual ones? Because I have manually selected some rois (iscell to not a cell) and I notice that depending on if I open the combined folder or the individual planes that does not get updated everywhere (when I work on the combined data I do not see changes in the individual plane folder...). 
Maybe that could be an issue?

**Comment by javidaf** [comment]
yes, true I extract data from individual planes(folders), I used the combined folder first, but then found trouble. 

> Okay... I might have fround the problem. Do you load the data from the combined folder or from the individual ones? Because I have manually selected some rois (iscell to not a cell) and I notice that depending on if I open the combined folder or the individual planes that does not get updated everywhere (when I work on the combined data I do not see changes in the individual plane folder...). Maybe that could be an issue?
